# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vaibhav Takawadekar
full_name: Vaibhav Takawadekar
email: vaibhav.takawadekar@hotmail.com
email2: takawadekarvb19.extc@coeptech.ac.in
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vaibhavtakawadekar.github.io/ghpage/" # the base hostname & protocol for your site
github_username:  vaibhavtakawadekar
twitter_username: vaib_3
linkedin_username: vaibhav-takawadekar-b8a31114b
# stackoverflow: 5080995/martianwars
include: ['_pages']
footer-links-active:
  stackoverflow: true

# Build settings
markdown: kramdown
gems:
  - jekyll-seo-tag
  - jekyll-redirect-from
